/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "hd44780_lcd.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ApiRequest, ApiRequest, AUTO)


PB_BIND(MoveCursor, MoveCursor, AUTO)


PB_BIND(WriteText, WriteText, AUTO)


PB_BIND(ConfigureDisplay, ConfigureDisplay, AUTO)


PB_BIND(ShiftDisplay, ShiftDisplay, AUTO)





